### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by dhernandez0** [germain-hug/S2DNet-Minimal#1]
Thanks for sharing the code. Please, could you clarify what image normalization was applied during training?

**Comment by germain-hug** [comment]
Sorry about the late response!
The normalization is the same as the one used in the VGG-16 implementation, ie. a mean of (0.485, 0.456, 0.406) and std of (0.229, 0.224, 0.225). You can find an example of S2DNet being used here: https://github.com/cvg/pixloc/blob/master/pixloc/pixlib/models/s2dnet.py
