### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lea-v** [germain-hug/S2DNet-Minimal#2]
Thanks for sharing this code! 
The readme file sounds like you are willing to share the code and trained model but your repo does not have a license at the moment.
Is it purposedly meant not to be used or is it that a chosen license is missing? 
See https://choosealicense.com/no-permission/ to better understand my inquiry

Thanks in advance for any clarification

**Comment by germain-hug** [comment]
Apologies I indeed forgot to add the license, just pushed it :)
Thanks!

**Comment by lea-v** [comment]
Thanks a lot for adding it, and for choosing a permissive one
